
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module EE314exp0(

	//////////// LED //////////
	output		     [7:0]		LEDR,

	//////////// SW //////////
	input 		     [7:0]		SW
);
wire [3:0] sub;
wire [3:0] comp;
OurSubtractorVerilog my_subtractor(

.a(SW[7:4]),
.b(SW[3:0]),
.subout(sub),
.compout(comp)
);


assign LEDR[3:0] = comp;
assign LEDR[7:4] = sub;



endmodule